# Generated by Django 5.0.4 on 2024-04-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0003_alter_category_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='picture',
            field=models.ImageField(default='', upload_to='catIcons'),
            preserve_default=False,
        ),
    ]
